      SUBROUTINE Suxu_bepvebxemvexccx(P1,ANS)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL_REAL_DECAY)
C  
C FOR PROCESS : u~ u -> b e+ ve b~ e- ve~ c c~  
C  
C Crossing   1 is u~ u -> b e+ ve b~ e- ve~ c c~  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      Include "../genps.inc"
     
     
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (             NCOMB=1024, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL_REAL_DECAY),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL_REAL_DECAY,NCOMB),NTRY
      REAL*8 T, P(0:3,NEXTERNAL_REAL_DECAY)
      REAL*8 uxu_bepvebxemvexccx
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL_REAL_DECAY,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL_REAL_DECAY), I
      LOGICAL GOODHEL(NCOMB,NCROSS)
      INTEGER NGRAPHS
      REAL*8 hwgt, xtot, xtry, xrej, xr, yfrac(0:ncomb)
      INTEGER idum, ngood, igood(ncomb), jhel, j, jj
      LOGICAL warned
      REAL     xran1
      EXTERNAL xran1
C  
C GLOBAL VARIABLES
C  
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_uxu_bepvebxemvexccx/  amp2,       jamp2

      character*79         hel_buff
      common/to_helicity/  hel_buff

      REAL*8 POL(2)
      common/to_polarization/ POL

      integer          isum_hel
      logical                    multi_channel
      common/to_matrix/isum_hel, multi_channel
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      common/to_mconfigs/mapconfig, iconfig
      DATA NTRY,IDUM /0,-1/
      DATA xtry, xrej, ngood /0,0,0/
      DATA warned/.false./
      
      SAVE yfrac, igood, jhel
      DATA NGRAPHS /    7/          
      DATA jamp2(0) /   6/          
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(IHEL,   1),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,   3),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,   4),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,   5),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,   6),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1,10) /-1,-1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,   9),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  10),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  11),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  12),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  15),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  16),IHEL=1,10) /-1,-1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  17),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  18),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  19),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  20),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  21),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  22),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  23),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  24),IHEL=1,10) /-1,-1,-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  25),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  26),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  27),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  28),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  29),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  30),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  31),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  32),IHEL=1,10) /-1,-1,-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  33),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  34),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  35),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  36),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  37),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  38),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  39),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  40),IHEL=1,10) /-1,-1,-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  41),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  42),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  43),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  44),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  45),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  46),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  47),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  48),IHEL=1,10) /-1,-1,-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  49),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  50),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  51),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  52),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  53),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  54),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  55),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  56),IHEL=1,10) /-1,-1,-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  57),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  58),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  59),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  60),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  61),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  62),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  63),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  64),IHEL=1,10) /-1,-1,-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  65),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  66),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  67),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  68),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  69),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  70),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  71),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  72),IHEL=1,10) /-1,-1,-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  73),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  74),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  75),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  76),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  77),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  78),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  79),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  80),IHEL=1,10) /-1,-1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  81),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  82),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  83),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  84),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  85),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  86),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  87),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  88),IHEL=1,10) /-1,-1,-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  89),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  90),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  91),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  92),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  93),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  94),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  95),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  96),IHEL=1,10) /-1,-1,-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  97),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  98),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  99),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 100),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 101),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 102),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 103),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 104),IHEL=1,10) /-1,-1,-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 105),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 106),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 107),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 108),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 109),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 110),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 111),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 112),IHEL=1,10) /-1,-1,-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 113),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 114),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 115),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 116),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 117),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 118),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 119),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 120),IHEL=1,10) /-1,-1,-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 121),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 122),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 123),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 124),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 125),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 126),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 127),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 128),IHEL=1,10) /-1,-1,-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 129),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 130),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 131),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 132),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 133),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 134),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 135),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 136),IHEL=1,10) /-1,-1, 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 137),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 138),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 139),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 140),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 141),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 142),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 143),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 144),IHEL=1,10) /-1,-1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 145),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 146),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 147),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 148),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 149),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 150),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 151),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 152),IHEL=1,10) /-1,-1, 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 153),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 154),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 155),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 156),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 157),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 158),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 159),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 160),IHEL=1,10) /-1,-1, 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 161),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 162),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 163),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 164),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 165),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 166),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 167),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 168),IHEL=1,10) /-1,-1, 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 169),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 170),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 171),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 172),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 173),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 174),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 175),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 176),IHEL=1,10) /-1,-1, 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 177),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 178),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 179),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 180),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 181),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 182),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 183),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 184),IHEL=1,10) /-1,-1, 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 185),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 186),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 187),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 188),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 189),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 190),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 191),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 192),IHEL=1,10) /-1,-1, 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 193),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 194),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 195),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 196),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 197),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 198),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 199),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 200),IHEL=1,10) /-1,-1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 201),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 202),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 203),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 204),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 205),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 206),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 207),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 208),IHEL=1,10) /-1,-1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 209),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 210),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 211),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 212),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 213),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 214),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 215),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 216),IHEL=1,10) /-1,-1, 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 217),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 218),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 219),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 220),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 221),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 222),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 223),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 224),IHEL=1,10) /-1,-1, 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 225),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 226),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 227),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 228),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 229),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 230),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 231),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 232),IHEL=1,10) /-1,-1, 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 233),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 234),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 235),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 236),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 237),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 238),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 239),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 240),IHEL=1,10) /-1,-1, 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 241),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 242),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 243),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 244),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 245),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 246),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 247),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 248),IHEL=1,10) /-1,-1, 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 249),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 250),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 251),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 252),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 253),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 254),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 255),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 256),IHEL=1,10) /-1,-1, 1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 257),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 258),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 259),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 260),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 261),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 262),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 263),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 264),IHEL=1,10) /-1, 1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 265),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 266),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 267),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 268),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 269),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 270),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 271),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 272),IHEL=1,10) /-1, 1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 273),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 274),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 275),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 276),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 277),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 278),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 279),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 280),IHEL=1,10) /-1, 1,-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 281),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 282),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 283),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 284),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 285),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 286),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 287),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 288),IHEL=1,10) /-1, 1,-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 289),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 290),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 291),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 292),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 293),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 294),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 295),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 296),IHEL=1,10) /-1, 1,-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 297),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 298),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 299),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 300),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 301),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 302),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 303),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 304),IHEL=1,10) /-1, 1,-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 305),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 306),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 307),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 308),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 309),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 310),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 311),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 312),IHEL=1,10) /-1, 1,-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 313),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 314),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 315),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 316),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 317),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 318),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 319),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 320),IHEL=1,10) /-1, 1,-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 321),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 322),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 323),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 324),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 325),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 326),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 327),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 328),IHEL=1,10) /-1, 1,-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 329),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 330),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 331),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 332),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 333),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 334),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 335),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 336),IHEL=1,10) /-1, 1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 337),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 338),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 339),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 340),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 341),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 342),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 343),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 344),IHEL=1,10) /-1, 1,-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 345),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 346),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 347),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 348),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 349),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 350),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 351),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 352),IHEL=1,10) /-1, 1,-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 353),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 354),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 355),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 356),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 357),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 358),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 359),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 360),IHEL=1,10) /-1, 1,-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 361),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 362),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 363),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 364),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 365),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 366),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 367),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 368),IHEL=1,10) /-1, 1,-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 369),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 370),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 371),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 372),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 373),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 374),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 375),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 376),IHEL=1,10) /-1, 1,-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 377),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 378),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 379),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 380),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 381),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 382),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 383),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 384),IHEL=1,10) /-1, 1,-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 385),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 386),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 387),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 388),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 389),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 390),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 391),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 392),IHEL=1,10) /-1, 1, 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 393),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 394),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 395),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 396),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 397),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 398),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 399),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 400),IHEL=1,10) /-1, 1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 401),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 402),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 403),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 404),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 405),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 406),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 407),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 408),IHEL=1,10) /-1, 1, 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 409),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 410),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 411),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 412),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 413),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 414),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 415),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 416),IHEL=1,10) /-1, 1, 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 417),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 418),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 419),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 420),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 421),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 422),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 423),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 424),IHEL=1,10) /-1, 1, 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 425),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 426),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 427),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 428),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 429),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 430),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 431),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 432),IHEL=1,10) /-1, 1, 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 433),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 434),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 435),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 436),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 437),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 438),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 439),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 440),IHEL=1,10) /-1, 1, 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 441),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 442),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 443),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 444),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 445),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 446),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 447),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 448),IHEL=1,10) /-1, 1, 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 449),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 450),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 451),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 452),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 453),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 454),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 455),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 456),IHEL=1,10) /-1, 1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 457),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 458),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 459),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 460),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 461),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 462),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 463),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 464),IHEL=1,10) /-1, 1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 465),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 466),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 467),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 468),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 469),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 470),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 471),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 472),IHEL=1,10) /-1, 1, 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 473),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 474),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 475),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 476),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 477),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 478),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 479),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 480),IHEL=1,10) /-1, 1, 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 481),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 482),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 483),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 484),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 485),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 486),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 487),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 488),IHEL=1,10) /-1, 1, 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 489),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 490),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 491),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 492),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 493),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 494),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 495),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 496),IHEL=1,10) /-1, 1, 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 497),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 498),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 499),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 500),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 501),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 502),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 503),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 504),IHEL=1,10) /-1, 1, 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 505),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 506),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 507),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 508),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 509),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 510),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 511),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 512),IHEL=1,10) /-1, 1, 1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 513),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 514),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 515),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 516),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 517),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 518),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 519),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 520),IHEL=1,10) / 1,-1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 521),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 522),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 523),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 524),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 525),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 526),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 527),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 528),IHEL=1,10) / 1,-1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 529),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 530),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 531),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 532),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 533),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 534),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 535),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 536),IHEL=1,10) / 1,-1,-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 537),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 538),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 539),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 540),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 541),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 542),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 543),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 544),IHEL=1,10) / 1,-1,-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 545),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 546),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 547),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 548),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 549),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 550),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 551),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 552),IHEL=1,10) / 1,-1,-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 553),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 554),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 555),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 556),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 557),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 558),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 559),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 560),IHEL=1,10) / 1,-1,-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 561),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 562),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 563),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 564),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 565),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 566),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 567),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 568),IHEL=1,10) / 1,-1,-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 569),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 570),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 571),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 572),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 573),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 574),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 575),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 576),IHEL=1,10) / 1,-1,-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 577),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 578),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 579),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 580),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 581),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 582),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 583),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 584),IHEL=1,10) / 1,-1,-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 585),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 586),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 587),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 588),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 589),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 590),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 591),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 592),IHEL=1,10) / 1,-1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 593),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 594),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 595),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 596),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 597),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 598),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 599),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 600),IHEL=1,10) / 1,-1,-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 601),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 602),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 603),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 604),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 605),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 606),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 607),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 608),IHEL=1,10) / 1,-1,-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 609),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 610),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 611),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 612),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 613),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 614),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 615),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 616),IHEL=1,10) / 1,-1,-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 617),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 618),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 619),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 620),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 621),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 622),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 623),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 624),IHEL=1,10) / 1,-1,-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 625),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 626),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 627),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 628),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 629),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 630),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 631),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 632),IHEL=1,10) / 1,-1,-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 633),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 634),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 635),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 636),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 637),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 638),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 639),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 640),IHEL=1,10) / 1,-1,-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 641),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 642),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 643),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 644),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 645),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 646),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 647),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 648),IHEL=1,10) / 1,-1, 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 649),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 650),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 651),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 652),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 653),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 654),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 655),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 656),IHEL=1,10) / 1,-1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 657),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 658),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 659),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 660),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 661),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 662),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 663),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 664),IHEL=1,10) / 1,-1, 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 665),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 666),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 667),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 668),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 669),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 670),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 671),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 672),IHEL=1,10) / 1,-1, 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 673),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 674),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 675),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 676),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 677),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 678),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 679),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 680),IHEL=1,10) / 1,-1, 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 681),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 682),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 683),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 684),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 685),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 686),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 687),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 688),IHEL=1,10) / 1,-1, 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 689),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 690),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 691),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 692),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 693),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 694),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 695),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 696),IHEL=1,10) / 1,-1, 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 697),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 698),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 699),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 700),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 701),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 702),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 703),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 704),IHEL=1,10) / 1,-1, 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 705),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 706),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 707),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 708),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 709),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 710),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 711),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 712),IHEL=1,10) / 1,-1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 713),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 714),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 715),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 716),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 717),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 718),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 719),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 720),IHEL=1,10) / 1,-1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 721),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 722),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 723),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 724),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 725),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 726),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 727),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 728),IHEL=1,10) / 1,-1, 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 729),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 730),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 731),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 732),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 733),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 734),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 735),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 736),IHEL=1,10) / 1,-1, 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 737),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 738),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 739),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 740),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 741),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 742),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 743),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 744),IHEL=1,10) / 1,-1, 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 745),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 746),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 747),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 748),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 749),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 750),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 751),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 752),IHEL=1,10) / 1,-1, 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 753),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 754),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 755),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 756),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 757),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 758),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 759),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 760),IHEL=1,10) / 1,-1, 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 761),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 762),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 763),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 764),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 765),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 766),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 767),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 768),IHEL=1,10) / 1,-1, 1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 769),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 770),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 771),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 772),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 773),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 774),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 775),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 776),IHEL=1,10) / 1, 1,-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 777),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 778),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 779),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 780),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 781),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 782),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 783),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 784),IHEL=1,10) / 1, 1,-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 785),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 786),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 787),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 788),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 789),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 790),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 791),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 792),IHEL=1,10) / 1, 1,-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 793),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 794),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 795),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 796),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 797),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 798),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 799),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 800),IHEL=1,10) / 1, 1,-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 801),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 802),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 803),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 804),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 805),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 806),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 807),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 808),IHEL=1,10) / 1, 1,-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 809),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 810),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 811),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 812),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 813),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 814),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 815),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 816),IHEL=1,10) / 1, 1,-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 817),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 818),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 819),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 820),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 821),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 822),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 823),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 824),IHEL=1,10) / 1, 1,-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 825),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 826),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 827),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 828),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 829),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 830),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 831),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 832),IHEL=1,10) / 1, 1,-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 833),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 834),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 835),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 836),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 837),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 838),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 839),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 840),IHEL=1,10) / 1, 1,-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 841),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 842),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 843),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 844),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 845),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 846),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 847),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 848),IHEL=1,10) / 1, 1,-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 849),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 850),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 851),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 852),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 853),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 854),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 855),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 856),IHEL=1,10) / 1, 1,-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 857),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 858),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 859),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 860),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 861),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 862),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 863),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 864),IHEL=1,10) / 1, 1,-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 865),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 866),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 867),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 868),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 869),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 870),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 871),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 872),IHEL=1,10) / 1, 1,-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 873),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 874),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 875),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 876),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 877),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 878),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 879),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 880),IHEL=1,10) / 1, 1,-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 881),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 882),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 883),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 884),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 885),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 886),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 887),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 888),IHEL=1,10) / 1, 1,-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 889),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 890),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 891),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 892),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 893),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 894),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 895),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 896),IHEL=1,10) / 1, 1,-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 897),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 898),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 899),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 900),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 901),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 902),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 903),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 904),IHEL=1,10) / 1, 1, 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 905),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 906),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 907),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 908),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 909),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 910),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 911),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 912),IHEL=1,10) / 1, 1, 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 913),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 914),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 915),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 916),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 917),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 918),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 919),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 920),IHEL=1,10) / 1, 1, 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 921),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 922),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 923),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 924),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 925),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 926),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 927),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 928),IHEL=1,10) / 1, 1, 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 929),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 930),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 931),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 932),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 933),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 934),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 935),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 936),IHEL=1,10) / 1, 1, 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 937),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 938),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 939),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 940),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 941),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 942),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 943),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 944),IHEL=1,10) / 1, 1, 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 945),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 946),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 947),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 948),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 949),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 950),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 951),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 952),IHEL=1,10) / 1, 1, 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 953),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 954),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 955),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 956),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 957),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 958),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 959),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 960),IHEL=1,10) / 1, 1, 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 961),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 962),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 963),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 964),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 965),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 966),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 967),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 968),IHEL=1,10) / 1, 1, 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 969),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 970),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 971),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 972),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 973),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 974),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 975),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 976),IHEL=1,10) / 1, 1, 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 977),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 978),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 979),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 980),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 981),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 982),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 983),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 984),IHEL=1,10) / 1, 1, 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 985),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 986),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 987),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 988),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 989),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 990),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 991),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 992),IHEL=1,10) / 1, 1, 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 993),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 994),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 995),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 996),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 997),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 998),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 999),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,1000),IHEL=1,10) / 1, 1, 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,1001),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,1002),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,1003),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,1004),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,1005),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,1006),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,1007),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,1008),IHEL=1,10) / 1, 1, 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,1009),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,1010),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,1011),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,1012),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,1013),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,1014),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,1015),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,1016),IHEL=1,10) / 1, 1, 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,1017),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,1018),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,1019),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,1020),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,1021),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,1022),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,1023),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,1024),IHEL=1,10) / 1, 1, 1, 1, 1, 1, 1, 1, 1, 1/
      DATA (  IC(IHEL,  1),IHEL=1,10) / 1, 2, 3, 4, 5, 6, 7, 8, 9,10/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      CALL SWITCHMOM(P1,P,IC(1,IPROC),JC,NEXTERNAL_REAL_DECAY)
      DO IHEL=1,NEXTERNAL_REAL_DECAY
         JC(IHEL) = +1
      ENDDO
       
      IF (multi_channel) THEN
          DO IHEL=1,NGRAPHS
              amp2(ihel)=0d0
          ENDDO
          DO IHEL=1,int(jamp2(0))
              jamp2(ihel)=0d0
          ENDDO
      ENDIF
      ANS(IPROC) = 0D0
      write(hel_buff,'(16i5)') (0,i=1,NEXTERNAL_REAL_DECAY)
      IF (ISUM_HEL .EQ. 0 .OR. NTRY .LT. 10) THEN
          DO IHEL=1,NCOMB
             IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
                 T=uxu_bepvebxemvexccx(P ,NHEL(1,IHEL),JC(1))            
               DO JJ=1,nincoming
                 IF(POL(JJ).NE.1d0.AND.
     &              NHEL(JJ,IHEL).EQ.INT(SIGN(1d0,POL(JJ)))) THEN
                   T=T*ABS(POL(JJ))
                 ELSE IF(POL(JJ).NE.1d0)THEN
                   T=T*(2d0-ABS(POL(JJ)))
                 ENDIF
               ENDDO
               ANS(IPROC)=ANS(IPROC)+T
               IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL,IPROC)) THEN
                   GOODHEL(IHEL,IPROC)=.TRUE.
                   NGOOD = NGOOD +1
                   IGOOD(NGOOD) = IHEL
               ENDIF
             ENDIF
          ENDDO
          JHEL = 1
          ISUM_HEL=MIN(ISUM_HEL,NGOOD)
      ELSE              !RANDOM HELICITY
          DO J=1,ISUM_HEL
              JHEL=JHEL+1
              IF (JHEL .GT. NGOOD) JHEL=1
              HWGT = REAL(NGOOD)/REAL(ISUM_HEL)
              IHEL = IGOOD(JHEL)
              T=uxu_bepvebxemvexccx(P ,NHEL(1,IHEL),JC(1))            
              DO JJ=1,nincoming
                IF(POL(JJ).NE.1d0.AND.
     &             NHEL(JJ,IHEL).EQ.INT(SIGN(1d0,POL(JJ)))) THEN
                  T=T*ABS(POL(JJ))
                ELSE IF(POL(JJ).NE.1d0)THEN
                  T=T*(2d0-ABS(POL(JJ)))
                ENDIF
              ENDDO
              ANS(IPROC)=ANS(IPROC)+T*HWGT
          ENDDO
          IF (ISUM_HEL .EQ. 1) THEN
              WRITE(HEL_BUFF,'(16i5)')(NHEL(i,IHEL),i=1,NEXTERNAL_REAL_DECAY)
          ENDIF
      ENDIF
      IF (MULTI_CHANNEL) THEN
          XTOT=0D0
          DO IHEL=1,MAPCONFIG(0)
              XTOT=XTOT+AMP2(MAPCONFIG(IHEL))
          ENDDO
          IF (XTOT.NE.0D0) THEN
              ANS(IPROC)=ANS(IPROC)*AMP2(MAPCONFIG(ICONFIG))/XTOT
          ELSE
              ANS(IPROC)=0D0
          ENDIF
      ENDIF
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      ENDDO
      END
       
       
      REAL*8 FUNCTION uxu_bepvebxemvexccx(P,NHEL,IC)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL_REAL_DECAY)
C  
C FOR PROCESS : u~ u -> b e+ ve b~ e- ve~ c c~  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER (NGRAPHS=   7,NEIGEN=  6) 
      include "../genps.inc"
     
     
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  33, NCOLOR=   6) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL_REAL_DECAY)
      INTEGER NHEL(NEXTERNAL_REAL_DECAY), IC(NEXTERNAL_REAL_DECAY)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_uxu_bepvebxemvexccx/  amp2,       jamp2
      include "../coupl.inc"
C  
C COLOR DATA
C  
      DATA Denom(1  )/            6/                                       
      DATA (CF(i,1  ),i=1  ,6  ) /     8,   -1,   -2,    7,   -2,    7/    
C               T[ 1,10]T[ 9, 6]T[ 3, 2]                                   
      DATA Denom(2  )/            6/                                       
      DATA (CF(i,2  ),i=1  ,6  ) /    -1,    8,    7,   -2,    7,   -2/    
C               T[ 1, 6]T[ 3,10]T[ 9, 2]                                   
      DATA Denom(3  )/            6/                                       
      DATA (CF(i,3  ),i=1  ,6  ) /    -2,    7,    8,   -2,    7,   -1/    
C               T[ 1, 6]T[ 3,10]T[ 9, 2]                                   
      DATA Denom(4  )/            6/                                       
      DATA (CF(i,4  ),i=1  ,6  ) /     7,   -2,   -2,    8,   -1,    7/    
C               T[ 1,10]T[ 9, 6]T[ 3, 2]                                   
      DATA Denom(5  )/            6/                                       
      DATA (CF(i,5  ),i=1  ,6  ) /    -2,    7,    7,   -1,    8,   -2/    
C               T[ 9, 2]T[ 1, 6]T[ 3,10]                                   
      DATA Denom(6  )/            6/                                       
      DATA (CF(i,6  ),i=1  ,6  ) /     7,   -2,   -1,    7,   -2,    8/    
C               T[ 3, 2]T[ 1,10]T[ 9, 6]                                   
C ----------
C BEGIN CODE
C ----------
      CALL OXXXXX(P(0,1   ),ZERO ,NHEL(1   ),-1*IC(1   ),W(1,1   ))        
      CALL IXXXXX(P(0,2   ),ZERO ,NHEL(2   ),+1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),BMASS ,NHEL(3   ),+1*IC(3   ),W(1,3   ))       
      CALL IXXXXX(P(0,4   ),ZERO ,NHEL(4   ),-1*IC(4   ),W(1,4   ))        
      CALL OXXXXX(P(0,5   ),ZERO ,NHEL(5   ),+1*IC(5   ),W(1,5   ))        
      CALL IXXXXX(P(0,6   ),BMASS ,NHEL(6   ),-1*IC(6   ),W(1,6   ))       
      CALL OXXXXX(P(0,7   ),ZERO ,NHEL(7   ),+1*IC(7   ),W(1,7   ))        
      CALL IXXXXX(P(0,8   ),ZERO ,NHEL(8   ),-1*IC(8   ),W(1,8   ))        
      CALL OXXXXX(P(0,9   ),ZERO ,NHEL(9   ),+1*IC(9   ),W(1,9   ))        
      CALL IXXXXX(P(0,10  ),ZERO ,NHEL(10  ),-1*IC(10  ),W(1,10  ))        
      CALL JIOXXX(W(1,4   ),W(1,5   ),GWF ,WMASS   ,WWIDTH  ,W(1,11  ))    
      CALL JIOXXX(W(1,8   ),W(1,7   ),GWF ,WMASS   ,WWIDTH  ,W(1,12  ))    
      CALL JIOXXX(W(1,10  ),W(1,9   ),GG ,ZERO    ,ZERO    ,W(1,13  ))     
      CALL FVOXXX(W(1,3   ),W(1,11  ),GWF ,TMASS   ,TWIDTH  ,W(1,14  ))    
      CALL FVOXXX(W(1,1   ),W(1,13  ),GG ,ZERO    ,ZERO    ,W(1,15  ))     
      CALL JIOXXX(W(1,2   ),W(1,15  ),GG ,ZERO    ,ZERO    ,W(1,16  ))     
      CALL FVOXXX(W(1,14  ),W(1,16  ),GG ,TMASS   ,TWIDTH  ,W(1,17  ))     
      CALL IOVXXX(W(1,6   ),W(1,17  ),W(1,12  ),GWF ,AMP(1   ))            
      CALL FVIXXX(W(1,2   ),W(1,13  ),GG ,ZERO    ,ZERO    ,W(1,18  ))     
      CALL JIOXXX(W(1,18  ),W(1,1   ),GG ,ZERO    ,ZERO    ,W(1,19  ))     
      CALL FVOXXX(W(1,14  ),W(1,19  ),GG ,TMASS   ,TWIDTH  ,W(1,20  ))     
      CALL IOVXXX(W(1,6   ),W(1,20  ),W(1,12  ),GWF ,AMP(2   ))            
      CALL JIOXXX(W(1,2   ),W(1,1   ),GG ,ZERO    ,ZERO    ,W(1,21  ))     
      CALL FVOXXX(W(1,14  ),W(1,13  ),GG ,TMASS   ,TWIDTH  ,W(1,22  ))     
      CALL FVOXXX(W(1,22  ),W(1,21  ),GG ,TMASS   ,TWIDTH  ,W(1,23  ))     
      CALL IOVXXX(W(1,6   ),W(1,23  ),W(1,12  ),GWF ,AMP(3   ))            
      CALL JVVXXX(W(1,13  ),W(1,21  ),G ,ZERO    ,ZERO    ,W(1,24  ))      
      CALL FVOXXX(W(1,14  ),W(1,24  ),GG ,TMASS   ,TWIDTH  ,W(1,25  ))     
      CALL IOVXXX(W(1,6   ),W(1,25  ),W(1,12  ),GWF ,AMP(4   ))            
      CALL FVIXXX(W(1,10  ),W(1,21  ),GG ,ZERO    ,ZERO    ,W(1,26  ))     
      CALL JIOXXX(W(1,26  ),W(1,9   ),GG ,ZERO    ,ZERO    ,W(1,27  ))     
      CALL FVOXXX(W(1,14  ),W(1,27  ),GG ,TMASS   ,TWIDTH  ,W(1,28  ))     
      CALL IOVXXX(W(1,6   ),W(1,28  ),W(1,12  ),GWF ,AMP(5   ))            
      CALL FVOXXX(W(1,9   ),W(1,21  ),GG ,ZERO    ,ZERO    ,W(1,29  ))     
      CALL JIOXXX(W(1,10  ),W(1,29  ),GG ,ZERO    ,ZERO    ,W(1,30  ))     
      CALL FVOXXX(W(1,14  ),W(1,30  ),GG ,TMASS   ,TWIDTH  ,W(1,31  ))     
      CALL IOVXXX(W(1,6   ),W(1,31  ),W(1,12  ),GWF ,AMP(6   ))            
      CALL FVOXXX(W(1,14  ),W(1,21  ),GG ,TMASS   ,TWIDTH  ,W(1,32  ))     
      CALL FVOXXX(W(1,32  ),W(1,13  ),GG ,TMASS   ,TWIDTH  ,W(1,33  ))     
      CALL IOVXXX(W(1,6   ),W(1,33  ),W(1,12  ),GWF ,AMP(7   ))            
      JAMP(   1) = +AMP(   1)-AMP(   4)
      JAMP(   2) = +AMP(   2)+AMP(   4)
      JAMP(   3) = +AMP(   3)
      JAMP(   4) = +AMP(   5)
      JAMP(   5) = +AMP(   6)
      JAMP(   6) = +AMP(   7)
      uxu_bepvebxemvexccx = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          uxu_bepvebxemvexccx =uxu_bepvebxemvexccx+ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO
      Do I = 1, NGRAPHS
          amp2(i)=amp2(i)+amp(i)*dconjg(amp(i))
      Enddo
      Do I = 1, NCOLOR
          Jamp2(i)=Jamp2(i)+Jamp(i)*dconjg(Jamp(i))
      Enddo
C      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
       
       
