      SUBROUTINE SREALMTRX_169(P1,ANS)
C  
C Generated by MadGraph II                                              
C MadGraph StandAlone Version
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : g b~ -> h e+ e- b~ g  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      Include "nexternal.inc"
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (             NCOMB=  64, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=  68)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 REALMTRX_169
      REAL*8 ZERO
      PARAMETER(ZERO=0d0)
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL), I,L,K
      LOGICAL GOODHEL(NCOMB,NCROSS)
      DATA NTRY/0/
      INTEGER NGOOD,igood(ncomb),jhel
      data ngood /0/
      save igood,jhel
      REAL*8 hwgt
      integer maxamps
      parameter (maxamps=6000)
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_Ramps_169/  amp2,       jamp2

      integer j,jj
      integer max_bhel
      parameter ( max_bhel =          64 )

      INTEGER NCOLOR
      DATA NCOLOR   /   2/          
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(IHEL,   1),IHEL=1, 7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1, 7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,   3),IHEL=1, 7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,   4),IHEL=1, 7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,   5),IHEL=1, 7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,   6),IHEL=1, 7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1, 7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1, 7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,   9),IHEL=1, 7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  10),IHEL=1, 7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  11),IHEL=1, 7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  12),IHEL=1, 7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1, 7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1, 7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  15),IHEL=1, 7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  16),IHEL=1, 7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  17),IHEL=1, 7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  18),IHEL=1, 7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  19),IHEL=1, 7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  20),IHEL=1, 7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  21),IHEL=1, 7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  22),IHEL=1, 7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  23),IHEL=1, 7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  24),IHEL=1, 7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  25),IHEL=1, 7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  26),IHEL=1, 7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  27),IHEL=1, 7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  28),IHEL=1, 7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  29),IHEL=1, 7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  30),IHEL=1, 7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  31),IHEL=1, 7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  32),IHEL=1, 7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  33),IHEL=1, 7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  34),IHEL=1, 7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  35),IHEL=1, 7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  36),IHEL=1, 7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  37),IHEL=1, 7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  38),IHEL=1, 7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  39),IHEL=1, 7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  40),IHEL=1, 7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  41),IHEL=1, 7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  42),IHEL=1, 7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  43),IHEL=1, 7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  44),IHEL=1, 7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  45),IHEL=1, 7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  46),IHEL=1, 7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  47),IHEL=1, 7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  48),IHEL=1, 7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  49),IHEL=1, 7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  50),IHEL=1, 7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  51),IHEL=1, 7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  52),IHEL=1, 7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  53),IHEL=1, 7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  54),IHEL=1, 7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  55),IHEL=1, 7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  56),IHEL=1, 7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  57),IHEL=1, 7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  58),IHEL=1, 7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  59),IHEL=1, 7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  60),IHEL=1, 7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  61),IHEL=1, 7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  62),IHEL=1, 7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  63),IHEL=1, 7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  64),IHEL=1, 7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 7) / 1, 2, 3, 4, 5, 6, 7/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  96/
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      DO IHEL=1,NEXTERNAL
         JC(IHEL) = +1
      ENDDO
      DO IHEL=1,NGRAPHS
          amp2(ihel)=0d0
      ENDDO
      jamp2(0)=dble(NCOLOR)
      DO IHEL=1,int(jamp2(0))
          jamp2(ihel)=0d0
      ENDDO
      ANS(IPROC) = 0D0
          DO IHEL=1,NCOMB
             IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
                 T=REALMTRX_169(P1,NHEL(1,IHEL),IHEL,JC(1))              
               ANS(IPROC)=ANS(IPROC)+T
               IF (T .GT. 0D0 .AND. .NOT. GOODHEL(IHEL,IPROC)) THEN
                   GOODHEL(IHEL,IPROC)=.TRUE.
                   NGOOD = NGOOD +1
                   IGOOD(NGOOD) = IHEL
               ENDIF
             ENDIF
          ENDDO
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      ENDDO
      END
       
       
      REAL*8 FUNCTION REALMTRX_169(P,NHEL,HELL,IC)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : g b~ -> h e+ e- b~ g  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER (NGRAPHS=  68,NEIGEN=  2) 
      include "nexternal.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  88, NCOLOR=   2) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL), HELL
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      integer maxamps
      parameter (maxamps=6000)
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_Ramps_169/  amp2,       jamp2
      integer max_bhel
      parameter ( max_bhel =          64 )
      include "coupl.inc"
C  
C COLOR DATA
C  
      DATA Denom(1  )/            3/                                       
      DATA (CF(i,1  ),i=1  ,2  ) /    16,   -2/                            
C               T[ 2, 6, 1, 7]                                             
      DATA Denom(2  )/            3/                                       
      DATA (CF(i,2  ),i=1  ,2  ) /    -2,   16/                            
C               T[ 2, 6, 7, 1]                                             
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P(0,1   ),ZERO ,NHEL(1   ),-1*IC(1   ),W(1,1   ))        
      CALL OXXXXX(P(0,2   ),BMASS ,NHEL(2   ),-1*IC(2   ),W(1,2   ))       
      CALL SXXXXX(P(0,3   ),+1*IC(3   ),W(1,3   ))                         
      CALL IXXXXX(P(0,4   ),ZERO ,NHEL(4   ),-1*IC(4   ),W(1,4   ))        
      CALL OXXXXX(P(0,5   ),ZERO ,NHEL(5   ),+1*IC(5   ),W(1,5   ))        
      CALL IXXXXX(P(0,6   ),BMASS ,NHEL(6   ),-1*IC(6   ),W(1,6   ))       
      CALL VXXXXX(P(0,7   ),ZERO ,NHEL(7   ),+1*IC(7   ),W(1,7   ))        
      CALL FSOXXX(W(1,2   ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     8   ))                                                          
      CALL JIOXXX(W(1,4   ),W(1,5   ),GAL ,ZERO    ,AWIDTH  ,W(1,9   ))    
      CALL JVVXXX(W(1,7   ),W(1,1   ),G ,ZERO    ,ZERO    ,W(1,10  ))      
      CALL FVOXXX(W(1,8   ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,11  ))    
      CALL IOVXXX(W(1,6   ),W(1,11  ),W(1,10  ),GG ,AMP(1   ))             
      CALL JIOXXX(W(1,4   ),W(1,5   ),GZL ,ZMASS   ,ZWIDTH  ,W(1,12  ))    
      CALL FVOXXX(W(1,8   ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,13  ))    
      CALL IOVXXX(W(1,6   ),W(1,13  ),W(1,10  ),GG ,AMP(2   ))             
      CALL FVOXXX(W(1,2   ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,14  ))     
      CALL FSOXXX(W(1,14  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     15  ))                                                          
      CALL FVOXXX(W(1,15  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,16  ))    
      CALL IOVXXX(W(1,6   ),W(1,16  ),W(1,1   ),GG ,AMP(3   ))             
      CALL FVOXXX(W(1,15  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,17  ))    
      CALL IOVXXX(W(1,6   ),W(1,17  ),W(1,1   ),GG ,AMP(4   ))             
      CALL FVOXXX(W(1,11  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,18  ))     
      CALL IOVXXX(W(1,6   ),W(1,18  ),W(1,7   ),GG ,AMP(5   ))             
      CALL FVOXXX(W(1,13  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,19  ))     
      CALL IOVXXX(W(1,6   ),W(1,19  ),W(1,7   ),GG ,AMP(6   ))             
      CALL FVOXXX(W(1,8   ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,20  ))     
      CALL FVOXXX(W(1,20  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,21  ))    
      CALL IOVXXX(W(1,6   ),W(1,21  ),W(1,1   ),GG ,AMP(7   ))             
      CALL FVOXXX(W(1,20  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,22  ))    
      CALL IOVXXX(W(1,6   ),W(1,22  ),W(1,1   ),GG ,AMP(8   ))             
      CALL FVOXXX(W(1,11  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,23  ))     
      CALL IOVXXX(W(1,6   ),W(1,23  ),W(1,1   ),GG ,AMP(9   ))             
      CALL FVOXXX(W(1,13  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,24  ))     
      CALL IOVXXX(W(1,6   ),W(1,24  ),W(1,1   ),GG ,AMP(10  ))             
      CALL FVOXXX(W(1,8   ),W(1,10  ),GG ,BMASS   ,ZERO    ,W(1,25  ))     
      CALL IOVXXX(W(1,6   ),W(1,25  ),W(1,9   ),GAD ,AMP(11  ))            
      CALL IOVXXX(W(1,6   ),W(1,25  ),W(1,12  ),GZD ,AMP(12  ))            
      CALL FVOXXX(W(1,15  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,26  ))     
      CALL IOVXXX(W(1,6   ),W(1,26  ),W(1,9   ),GAD ,AMP(13  ))            
      CALL IOVXXX(W(1,6   ),W(1,26  ),W(1,12  ),GZD ,AMP(14  ))            
      CALL FVOXXX(W(1,8   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,27  ))     
      CALL FVOXXX(W(1,27  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,28  ))    
      CALL IOVXXX(W(1,6   ),W(1,28  ),W(1,7   ),GG ,AMP(15  ))             
      CALL FVOXXX(W(1,27  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,29  ))    
      CALL IOVXXX(W(1,6   ),W(1,29  ),W(1,7   ),GG ,AMP(16  ))             
      CALL FVOXXX(W(1,20  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,30  ))     
      CALL IOVXXX(W(1,6   ),W(1,30  ),W(1,9   ),GAD ,AMP(17  ))            
      CALL IOVXXX(W(1,6   ),W(1,30  ),W(1,12  ),GZD ,AMP(18  ))            
      CALL FVOXXX(W(1,27  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,31  ))     
      CALL IOVXXX(W(1,6   ),W(1,31  ),W(1,9   ),GAD ,AMP(19  ))            
      CALL IOVXXX(W(1,6   ),W(1,31  ),W(1,12  ),GZD ,AMP(20  ))            
      CALL FVOXXX(W(1,2   ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,32  ))    
      CALL FSOXXX(W(1,32  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     33  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,33  ),W(1,10  ),GG ,AMP(21  ))             
      CALL FVOXXX(W(1,2   ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,34  ))    
      CALL FSOXXX(W(1,34  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     35  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,35  ),W(1,10  ),GG ,AMP(22  ))             
      CALL FVOXXX(W(1,14  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,36  ))    
      CALL FSOXXX(W(1,36  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     37  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,37  ),W(1,1   ),GG ,AMP(23  ))             
      CALL FVOXXX(W(1,14  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,38  ))    
      CALL FSOXXX(W(1,38  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     39  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,39  ),W(1,1   ),GG ,AMP(24  ))             
      CALL FVOXXX(W(1,33  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,40  ))     
      CALL IOVXXX(W(1,6   ),W(1,40  ),W(1,7   ),GG ,AMP(25  ))             
      CALL FVOXXX(W(1,35  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,41  ))     
      CALL IOVXXX(W(1,6   ),W(1,41  ),W(1,7   ),GG ,AMP(26  ))             
      CALL FVOXXX(W(1,32  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,42  ))     
      CALL FSOXXX(W(1,42  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     43  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,43  ),W(1,1   ),GG ,AMP(27  ))             
      CALL FVOXXX(W(1,34  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,44  ))     
      CALL FSOXXX(W(1,44  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     45  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,45  ),W(1,1   ),GG ,AMP(28  ))             
      CALL FVOXXX(W(1,33  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,46  ))     
      CALL IOVXXX(W(1,6   ),W(1,46  ),W(1,1   ),GG ,AMP(29  ))             
      CALL FVOXXX(W(1,35  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,47  ))     
      CALL IOVXXX(W(1,6   ),W(1,47  ),W(1,1   ),GG ,AMP(30  ))             
      CALL FVOXXX(W(1,32  ),W(1,10  ),GG ,BMASS   ,ZERO    ,W(1,48  ))     
      CALL IOSXXX(W(1,6   ),W(1,48  ),W(1,3   ),GHBOT ,AMP(31  ))          
      CALL FVOXXX(W(1,34  ),W(1,10  ),GG ,BMASS   ,ZERO    ,W(1,49  ))     
      CALL IOSXXX(W(1,6   ),W(1,49  ),W(1,3   ),GHBOT ,AMP(32  ))          
      CALL FVOXXX(W(1,36  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,50  ))     
      CALL IOSXXX(W(1,6   ),W(1,50  ),W(1,3   ),GHBOT ,AMP(33  ))          
      CALL FVOXXX(W(1,38  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,51  ))     
      CALL IOSXXX(W(1,6   ),W(1,51  ),W(1,3   ),GHBOT ,AMP(34  ))          
      CALL FVOXXX(W(1,32  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,52  ))     
      CALL FSOXXX(W(1,52  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     53  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,53  ),W(1,7   ),GG ,AMP(35  ))             
      CALL FVOXXX(W(1,34  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,54  ))     
      CALL FSOXXX(W(1,54  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     55  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,55  ),W(1,7   ),GG ,AMP(36  ))             
      CALL FVOXXX(W(1,42  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,56  ))     
      CALL IOSXXX(W(1,6   ),W(1,56  ),W(1,3   ),GHBOT ,AMP(37  ))          
      CALL FVOXXX(W(1,44  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,57  ))     
      CALL IOSXXX(W(1,6   ),W(1,57  ),W(1,3   ),GHBOT ,AMP(38  ))          
      CALL FVOXXX(W(1,52  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,58  ))     
      CALL IOSXXX(W(1,6   ),W(1,58  ),W(1,3   ),GHBOT ,AMP(39  ))          
      CALL FVOXXX(W(1,54  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,59  ))     
      CALL IOSXXX(W(1,6   ),W(1,59  ),W(1,3   ),GHBOT ,AMP(40  ))          
      CALL JVSXXX(W(1,12  ),W(1,3   ),GZZH ,ZMASS   ,ZWIDTH  ,W(1,         
     &     60  ))                                                          
      CALL FVOXXX(W(1,2   ),W(1,60  ),GZD ,BMASS   ,ZERO    ,W(1,61  ))    
      CALL IOVXXX(W(1,6   ),W(1,61  ),W(1,10  ),GG ,AMP(41  ))             
      CALL FVOXXX(W(1,14  ),W(1,60  ),GZD ,BMASS   ,ZERO    ,W(1,62  ))    
      CALL IOVXXX(W(1,6   ),W(1,62  ),W(1,1   ),GG ,AMP(42  ))             
      CALL FVOXXX(W(1,61  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,63  ))     
      CALL IOVXXX(W(1,6   ),W(1,63  ),W(1,7   ),GG ,AMP(43  ))             
      CALL FVOXXX(W(1,61  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,64  ))     
      CALL IOVXXX(W(1,6   ),W(1,64  ),W(1,1   ),GG ,AMP(44  ))             
      CALL FVOXXX(W(1,2   ),W(1,10  ),GG ,BMASS   ,ZERO    ,W(1,65  ))     
      CALL FVOXXX(W(1,65  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,66  ))    
      CALL IOSXXX(W(1,6   ),W(1,66  ),W(1,3   ),GHBOT ,AMP(45  ))          
      CALL FVOXXX(W(1,65  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,67  ))    
      CALL IOSXXX(W(1,6   ),W(1,67  ),W(1,3   ),GHBOT ,AMP(46  ))          
      CALL FVOXXX(W(1,14  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,68  ))     
      CALL FVOXXX(W(1,68  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,69  ))    
      CALL IOSXXX(W(1,6   ),W(1,69  ),W(1,3   ),GHBOT ,AMP(47  ))          
      CALL FVOXXX(W(1,68  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,70  ))    
      CALL IOSXXX(W(1,6   ),W(1,70  ),W(1,3   ),GHBOT ,AMP(48  ))          
      CALL FVOXXX(W(1,2   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,71  ))     
      CALL FVOXXX(W(1,71  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,72  ))    
      CALL FSOXXX(W(1,72  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     73  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,73  ),W(1,7   ),GG ,AMP(49  ))             
      CALL FVOXXX(W(1,71  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,74  ))    
      CALL FSOXXX(W(1,74  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     75  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,75  ),W(1,7   ),GG ,AMP(50  ))             
      CALL FVOXXX(W(1,71  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,76  ))     
      CALL FVOXXX(W(1,76  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,77  ))    
      CALL IOSXXX(W(1,6   ),W(1,77  ),W(1,3   ),GHBOT ,AMP(51  ))          
      CALL FVOXXX(W(1,76  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,78  ))    
      CALL IOSXXX(W(1,6   ),W(1,78  ),W(1,3   ),GHBOT ,AMP(52  ))          
      CALL FVOXXX(W(1,72  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,79  ))     
      CALL IOSXXX(W(1,6   ),W(1,79  ),W(1,3   ),GHBOT ,AMP(53  ))          
      CALL FVOXXX(W(1,74  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,80  ))     
      CALL IOSXXX(W(1,6   ),W(1,80  ),W(1,3   ),GHBOT ,AMP(54  ))          
      CALL IOVXXX(W(1,6   ),W(1,65  ),W(1,60  ),GZD ,AMP(55  ))            
      CALL IOVXXX(W(1,6   ),W(1,68  ),W(1,60  ),GZD ,AMP(56  ))            
      CALL FVOXXX(W(1,71  ),W(1,60  ),GZD ,BMASS   ,ZERO    ,W(1,81  ))    
      CALL IOVXXX(W(1,6   ),W(1,81  ),W(1,7   ),GG ,AMP(57  ))             
      CALL IOVXXX(W(1,6   ),W(1,76  ),W(1,60  ),GZD ,AMP(58  ))            
      CALL FSOXXX(W(1,65  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     82  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,82  ),W(1,9   ),GAD ,AMP(59  ))            
      CALL IOVXXX(W(1,6   ),W(1,82  ),W(1,12  ),GZD ,AMP(60  ))            
      CALL FSOXXX(W(1,68  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     83  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,83  ),W(1,9   ),GAD ,AMP(61  ))            
      CALL IOVXXX(W(1,6   ),W(1,83  ),W(1,12  ),GZD ,AMP(62  ))            
      CALL FSOXXX(W(1,71  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     84  ))                                                          
      CALL FVOXXX(W(1,84  ),W(1,9   ),GAD ,BMASS   ,ZERO    ,W(1,85  ))    
      CALL IOVXXX(W(1,6   ),W(1,85  ),W(1,7   ),GG ,AMP(63  ))             
      CALL FVOXXX(W(1,84  ),W(1,12  ),GZD ,BMASS   ,ZERO    ,W(1,86  ))    
      CALL IOVXXX(W(1,6   ),W(1,86  ),W(1,7   ),GG ,AMP(64  ))             
      CALL FSOXXX(W(1,76  ),W(1,3   ),GHBOT ,BMASS   ,ZERO    ,W(1,        
     &     87  ))                                                          
      CALL IOVXXX(W(1,6   ),W(1,87  ),W(1,9   ),GAD ,AMP(65  ))            
      CALL IOVXXX(W(1,6   ),W(1,87  ),W(1,12  ),GZD ,AMP(66  ))            
      CALL FVOXXX(W(1,84  ),W(1,7   ),GG ,BMASS   ,ZERO    ,W(1,88  ))     
      CALL IOVXXX(W(1,6   ),W(1,88  ),W(1,9   ),GAD ,AMP(67  ))            
      CALL IOVXXX(W(1,6   ),W(1,88  ),W(1,12  ),GZD ,AMP(68  ))            
      JAMP(   1) = +AMP(   1)+AMP(   2)-AMP(   5)-AMP(   6)+AMP(  11)
     &             +AMP(  12)-AMP(  15)-AMP(  16)-AMP(  19)-AMP(  20)
     &             +AMP(  21)+AMP(  22)-AMP(  25)-AMP(  26)+AMP(  31)
     &             +AMP(  32)-AMP(  35)-AMP(  36)-AMP(  39)-AMP(  40)
     &             +AMP(  41)-AMP(  43)+AMP(  45)+AMP(  46)-AMP(  49)
     &             -AMP(  50)-AMP(  51)-AMP(  52)-AMP(  53)-AMP(  54)
     &             +AMP(  55)-AMP(  57)-AMP(  58)+AMP(  59)+AMP(  60)
     &             -AMP(  63)-AMP(  64)-AMP(  65)-AMP(  66)-AMP(  67)
     &             -AMP(  68)
      JAMP(   2) = -AMP(   1)-AMP(   2)-AMP(   3)-AMP(   4)-AMP(   7)
     &             -AMP(   8)-AMP(   9)-AMP(  10)-AMP(  11)-AMP(  12)
     &             -AMP(  13)-AMP(  14)-AMP(  17)-AMP(  18)-AMP(  21)
     &             -AMP(  22)-AMP(  23)-AMP(  24)-AMP(  27)-AMP(  28)
     &             -AMP(  29)-AMP(  30)-AMP(  31)-AMP(  32)-AMP(  33)
     &             -AMP(  34)-AMP(  37)-AMP(  38)-AMP(  41)-AMP(  42)
     &             -AMP(  44)-AMP(  45)-AMP(  46)-AMP(  47)-AMP(  48)
     &             -AMP(  55)-AMP(  56)-AMP(  59)-AMP(  60)-AMP(  61)
     &             -AMP(  62)
      REALMTRX_169 = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          REALMTRX_169 =REALMTRX_169+ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO
      Do I = 1, NGRAPHS
          amp2(i)=amp2(i)+amp(i)*dconjg(amp(i))
      Enddo
      Do I = 1, NCOLOR
          Jamp2(i)=Jamp2(i)+Jamp(i)*dconjg(Jamp(i))
      Enddo
      END
       
       
